project:
  type: website

website:
  title: "Phillips Lab"
  navbar:
    right:
      - people.qmd
      - projects.qmd
      - courses.qmd
      - blog.qmd

format:
  html:
    theme: 
      - cosmo
      - mytheme.scss
    css: styles.css
    toc: true
    page-layout: full
    mainfont: Playfair Display

editor: visual

